//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab29BooksAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public string Title { get; set; }
        public string Author { get; set; }
        public string Category { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<int> YearPublished { get; set; }
        public int BookID { get; set; }
    }
}
